---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: true
configure_osx: true
install_aws_cli: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: false
dockitems_remove: []
# - Launchpad
# - TV
# - Podcasts
# - 'App Store'
dockitems_persist: []
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: /Users/Shared/repos/forks/dotfiles/geerlingguy
# dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: /Users/Shared/repos/forks/dotfiles/geerlingguy
# dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

executable_temp_dir: $HOME/Downloads

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  # - autoconf
  - awscli
  - bash
  - bash-completion
  - cowsay
  # - doxygen
  # - gettext
  # - gifsicle
  - git
  # - github/gh/gh
  - go
  - gpg
  # - httpie
  - iperf
  - iproute2mac
  - jo
  - jq
  # - libevent
  - lnav
  - mas
  # - mcrypt
  - netcat
  - nmap
  - node
  # - nvm
  - oh-my-posh
  - openssl
  # - pv
  # - php
  - shellcheck
  - ssh-copy-id
  - readline
  # - sqlite
  - wget
  # - wrk
  - zsh-history-substring-search

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - jandedobbeleer/oh-my-posh

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - chromedriver
  - firefox
  - visual-studio-code
  - docker
  # - dropbox
  - google-chrome
  - handbrake
  - iterm2
  # - licecap
  - postman
  # - sequel-ace
  # - slack
  # - sublime-text
  - transmit
  # - zoom

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: 
  - { id: 497714887, name: "WebSSH" }
  - { id: 425424353, name: "The Unarchiver" }
  - { id: 803453959, name: "Slack" }
  - { id: 441258766, name: "Magnet" }
  - { id: 1484051912, name: "Find It Server" }
# mas_uninstalled_apps:
#   # - { id: 408981434, name: "iMovie" } 
#   - { id: 409183694, name: "Keynote" }
#   - { id: 409201541, name: "Pages" }
#   - { id: 409203825, name: "Numbers" }
#   - { id: 682658836, name: "GarageBand" }
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text.
configure_sublime: false
sublime_base_path: '~/Library/Application Support/Sublime Text'
sublime_config_path: "Packages/User"
sublime_package_control:
  - "DocBlockr"
  - "Dockerfile Syntax Highlighting"
  - "FileDiffs"
  - "GitHub Flavored Markdown Preview"
  - "Jinja2"
  - "Package Control"
  - "PHP-Twig"
  - "Pretty JSON"
  - "SublimeLinter"
  - "SublimeLinter-contrib-yamllint"
  - "TrailingSpaces"
  - "WordCount"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
